### ISSUE TITLE
SSL not working logged-in

### ISSUE THREAD

**Issue by skvaller** [osCommerce/osCommerce-V4#32]
<img width="960" alt="prob ssl" src="https://user-images.githubusercontent.com/37003762/209617516-6f6d59f0-b1db-476d-af5e-e0c46660ae69.png">
Since content is when logged-in is blocked I can't work with OSC at all? 
Can you help me?

**Comment by pan-oscom** [comment]
It happens if you select http+https access while installing. The backend can works only with http or https. So, you have to change these lines into admin/includes/local/configure.php:

define('HTTP_SERVER', 'https://osc.loc');
define('HTTPS_SERVER', 'https://osc.loc');
define('HTTP_CATALOG_SERVER', 'https://osc.loc');
define('HTTPS_CATALOG_SERVER', 'https://osc.loc');

They all must be https or http.
We will fix install script in the next update
