### ISSUE TITLE
Product identifiers, Model/SKU is "mixed up"? Missing MPN

### ISSUE THREAD

**Issue by oewean** [osCommerce/osCommerce-V4#42]
Just started to test and learning osCV4 and in products there is different product identifiers.

I think Model/SKU is "mixed up"

My thoughts about this is:
SKU: Stock keeping Unit is different from business to business, linked to a MPN, EAN etc. A SKU is a seller-defined identifier.
As it's used now, it's more like a Model / MPN (Manufacturer part number), A MPN is a manufacturer-defined identifier.

Orders, invoices, packing list, import etc. should use SKU as primary identifier, as this is the normal for warehouses to use to identify products.

I can rename this to SKU and use it as SKU, but it's good to be consistent.

The linked / structured data (application/ld+json) Report this as SKU, for example with use with Google.

Import / export use this as "Products Model"

I think it's important to have MPN as well (for use with linked / structured data, shoppingfeed etc), 
so **MPN should be added as a product identifier.**

**Comment by pan-oscom** [comment]
You are right, SKU is different from business to business.
Model/SKU field is SKU for your business and you can rename it as you want.
If you also want to use MPN, you can:
1) rename one of unused fields ASIN, EAN, UPC
2) use product property
3) write extension and add new field

I suggest you use our forum for such questions. You will receive an answer faster.

**Comment by jessicana** [comment]
I think there is a bug with the Product identifiers. When all the identifiers are empty, I still can see the model field on the product listing page although it is empty. Suppose I don't want to assign a Model (SKU). Below is the backend with all the identifiers empty:

![image](https://github.com/osCommerce/osCommerce-V4/assets/7415824/53be3cf9-8605-4279-b0ce-4b8360bdec98)

The front end appears as follows:
![image](https://github.com/osCommerce/osCommerce-V4/assets/7415824/00befe40-c37c-4e82-9f2e-1f11ada37e49)

The model is there but technically it should disappear because the field is empty. 

Let's try and fill in all the fields and see how they appear on the product listing:

![image](https://github.com/osCommerce/osCommerce-V4/assets/7415824/a8f5b3e3-f980-4a4f-a23b-ff2c7e663292)

The front end appears as follows:
![image](https://github.com/osCommerce/osCommerce-V4/assets/7415824/a6372030-043f-42f3-b22f-cdb771f26f65)

Note that the ASIN doesn't appear on the front end although it is filled. Technically, the ASIN should've appeared in this scenario and the Model (SKU) should've disappeared in the first scenario when it was empty. 

**Is this a bug or do I have to adjust something in the settings?**

You can ignore the product details because that is coming from the properties. 

![image](https://github.com/osCommerce/osCommerce-V4/assets/7415824/218bf8e6-c3fe-4598-a957-0af10ffd66c1)

**Comment by pan-oscom** [comment]
Please use [our forum](https://www.oscommerce.com/forums/) for non-programing questions.

> The model is there but technically it should disappear because the field is empty.
Not really. Some of our clients would like to show the model field even with an empty value.

> Note that the ASIN doesn't appear on the front end although it is filled. Technically, the ASIN should've appeared in this scenario and the Model (SKU) should've disappeared in the first scenario when it was empty.
> Is this a bug or do I have to adjust something in the settings?
No. it's not a bug. It's just that there hasn't been a request to show ASIN on the frontend yet.

Actually, you can customize showing these fields in Theme designer:
![image](https://github.com/osCommerce/osCommerce-V4/assets/110422184/e34f0ba9-fb03-4f11-8040-b0748ca8e4bf)

For example, there is two choice for Show Model option: Yes and No. But we could add the third option: "Yes, if not empty"

**Comment by jessicana** [comment]
That is correct. Thanks. But as per the below, the ASIN is not in the properties. How can I add it?

![image](https://github.com/osCommerce/osCommerce-V4/assets/7415824/7bcc3f2e-84ff-4823-936e-155ef0c54662)

**Comment by pan-oscom** [comment]
It will be added in the next version of osCommerce
