### ISSUE TITLE
Can't add new tax rate

### ISSUE THREAD

**Issue by egoldsm** [osCommerce/osCommerce-V4#56]
![osc](https://github.com/osCommerce/osCommerce-V4/assets/78231559/4247181a-de0d-409b-90e6-29d149b0cebb)

Clicking the New Tax Rate button sends me to edit the existing tax rate (see screen grab)

**Comment by pan-oscom** [comment]
Unfortunately, we could not reproduce the issue. What osCommerce version are you using?

**Comment by pan-oscom** [comment]
After clicking the New Tax Rate button:
![image](https://github.com/osCommerce/osCommerce-V4/assets/110422184/81a44f93-9f3a-418e-a04d-65f7e37eea72)
As you can see, this is a new entry because the Tax Rate field is empty. The Tax Class Title and Zone fields are the same as in the existing record in that they go with the first value selected.

**Comment by egoldsm** [comment]
Ah, I see. Thanks for clearing that up for me.


Eric
